# Generated by Django 4.1.7 on 2023-10-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='exercises',
        ),
    ]
