# Generated by Django 4.1.7 on 2023-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_product_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='exercise3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
